# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost/declaration
    namespace: declaration.parliamentarians
    debug: true
  es:
    type: elasticsearch
    uri: http://localhost:9200
  locales:
    type: elasticsearch
    uri: http://localhost:9200
  stdout:
    type: file
    uri: stdout://
